### ISSUE TITLE
IMBA 7.00 Bug Compilation Issue

### ISSUE THREAD

**Issue by X-TheDark** [fcalife/dota_imba#153] opened 2017-04-06 16:35 UTC
Feel free to post anything here if you don't want to make a separate issue or something.

### Silencer - this one's mine
- [x] Some sound stuff that's played at the middle of the map;
- [x] Ulti blows speakers, as I feared - use playsoundforclient; (*FIXED*)

**Comment by EdvardasDlugauskas** [comment] 2017-04-06 16:42
Lion:

   * Mana Drain can be targeted at creeps without mana
    * Finger of Death Frog Panic ignores cast duration. This means there is no chance to avoid it for the targeted enemy.
    * Mana drain particles are yuuuggee. They are also kinda weird. Not a fan.

**Comment by Shushishtok** [comment] 2017-04-06 19:30
Ursa's and Lycan's innate passives are not in the list of innates skills.

**Comment by Eiddew** [comment] 2017-04-07 00:59
Slardar: Seems to gain and lose an ability any time he gets an item.

Also his Raincloud ability is only mentioned in what it does, not how to get it -- aghs is blank.

**Comment by Shushishtok** [comment] 2017-04-08 16:36
**Abbadon**
Ability layout of 4 skills while he has 5.
Mist Coil does not show damage.
Curse of Avernus does not slow the target nor increase allies' move and attack speed (at least not in the UI, though the target didn't look like it was slowed at all)

**Comment by Shushishtok** [comment] 2017-04-08 16:37
**Axe**
Enemies affected by Berserker's Call do not show bonus attack speed.
Battle Hunger's debuff ends immediately (instead of fading out) which looks bad visually.
Battle Hunter doesn't show base damage or % of maximum HP as damage.
Battle Hunger doesn't describe the amount of units needed to kill to dispel (just says that lasts until the target kills another unit), nor shows the amount of units needed to kill to dispel.
Counter Helix shows only the base damage, but not how much of Axe strength's is calculated in it.
Culling Blade shows "speed" (probably movement speed) as a constant, not percentage.
Axe doesn't heal from Culling Blade as described in the Trello or the infodump. Instead, it seems to add % of Axe's maximum health to the damage, which is not intended.
Either way, Culling Blade's % of Maximum Health is not shown in the description.
Culling Blade doesn't show duration, neither before or after purcashing Aghnaim Scepter.
Axe doesn't have talents of his own: he'll show the talent of the last hero whose talents were hovered on.

**Comment by Shushishtok** [comment] 2017-04-08 16:37
**Centaur**
Has an ability layout of 4 skills even though he has 5.
Return's stacking damage block does not work. 
Return works on towers.
Centaur doesn't have talents of his own: he'll show the talents of the last hero whose talents were hovered on.

**Comment by Shushishtok** [comment] 2017-04-08 16:38
**Lycan**
Doesn't get his innate.
(Probably) since Lycan doesn't have his innate, the cooldown can't be calculated properly. Either way, we can probably get rid of nettables calculations by using GetModifierStackCount() instead of setting it.
When using Shapeshift, an error pops because there is no IsServer() block in function modifier_imba_shapeshift_transform:OnCreated() function (line 980).

**Comment by Shushishtok** [comment] 2017-04-08 16:38
**Skadi **
Purcashing a skadi pops errors.

**Comment by Shushishtok** [comment] 2017-04-08 16:39
**Magnus**
Mid-Skewer activation should probably have a No Target behavior as it's practically possible to click anywhere to achieve the knockback effect.
Skewer does not "heaves" polarized enemies, which means that it ends prematurely and feels weird, especially if there's at least one enemy that was not polarized: that enemy would be heaved, while the other one stays at the location. They should always be heaved, and if Polarized, should be all heaved towards the exact same spot.
Using Manta while having Aghnaim Scepter "purges" the passive Empower on Magnus, causing the scepter duration to tick. When the duration ends, it stays there forever, but without the green circle. Casting Empower on self resets the process. The effect never ends, just stays there forever like this:
![image](https://cloud.githubusercontent.com/assets/15510811/24830656/03e8e126-1c93-11e7-90b8-8368178fb5bf.png)

This doesn't happen if you have no scepter, by the way. Having only Manta doesn't cause that bug.
It also pops errors in the console, line 392.

**Comment by Shushishtok** [comment] 2017-04-08 16:40
**Night Stalker**
Still has Void icon for his innate (we really gotta find something cool to replace that).

**Comment by Shushishtok** [comment] 2017-04-08 16:40
**Slardar**
Doesn't explain what is Rain Cloud or how you get it. Should probably add a "Upgradeable by Aghnaim Scepter", with the aghnaim scepter flavor showing up when holding a scepter.
Towers can be bashed with Bash of the Deep.

**Comment by Shushishtok** [comment] 2017-04-08 16:40
**Anti Mage**
Descriptions are not updated.

**Comment by Shushishtok** [comment] 2017-04-08 16:41
**Curseblade, Hellblade**
``DISPELLABLE_DEBUFF_LIST`` is not loaded anywhere (that I could find), which makes the actives fail completely.
Hellblade's file is missing, game's trying to route it into curseblade's file (?).

**Comment by Shushishtok** [comment] 2017-04-08 16:41
**Desolator**
Active particle is probable not being precached (I don't see a precache block), so it is invisible. Still deals damage and applies Desolator as intended

**Comment by Shushishtok** [comment] 2017-04-08 16:42
**Bloodseeker**
HP bonus indicator from Blood Rite has a weird placement above Bloodseeker - a bit too high, and it sometimes move to the right or to the left of the caster.
Thirst: Seems like the on-damage bonus only counts when the target is below 75% health. Is it intended?
Has no scepter upgrade: we wanted to do a scepter that pushes targets away from Blood Rite with Rupture on them, but we didn't in the end.
I've got some error after killing a hero just as he got hit by Blood Rite, but I can't repeat it.
```[VScript] Script Runtime Error: ...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:301: attempt to compare nil with number
stack traceback:
    ...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:301: in function <...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:285>
[VScript] Script Runtime Error: ...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:301: attempt to compare nil with number
stack traceback:
    ...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:301: in function <...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:285>
[VScript] Script Runtime Error: ...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:301: attempt to compare nil with number
stack traceback:
    ...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:301: in function <...465778740.vpk:scripts\vscripts\hero\hero_bloodseeker.lua:285>```

it seems to be very rare and needs extremely precise timing, so I think it's OK.

**Comment by Shushishtok** [comment] 2017-04-08 16:42
**Bounty Hunter**
HeadHunter is not innately assigned.
Ability layout is for 4 skills even though he has 5.

**Comment by Shushishtok** [comment] 2017-04-08 16:43
**Drow Ranger**
Doesn't get her innate assigned at game start.
Frost Arrows animation is replayed over and over when spamming the unit target spell. This is fixed by adding Immediate behavior to the skill.

**Comment by Shushishtok** [comment] 2017-04-08 16:43
**Faceless Void**
Descriptions are not updated, and talents are not named.
Time Lock has 100% proc at level 1.
Faceless Void has no animation for Chronosphere.
While in Chronosphere, a weird animated copy of himself stays at the cast location. This only happens when Faceless Void has Chronocharges when casting.
Chronosphere doesn't seem to interrupt Forced Movement of enemies, allowing Force Staff/Hurrican Pike to move units out of the Chronosphere. (wiki says it shouldn't happen)
Chronosphere doesn't seem to provide Flying vision in its area of effect.

**Comment by Shushishtok** [comment] 2017-04-08 16:44
**Juggernaut**
When using Blade Fury while Omnislashing, and Omnislash ends, Juggernaut doesn't keep the Blade Fury animation: the particle stays but he restarts his animations normally.
When Juggernaut gets his Aghnaim Scepter, Omnislash doesn't show how many slashes do you actually get (need to look at base value and add +3 to it, hard math for most players)
![image](https://cloud.githubusercontent.com/assets/15510811/24830703/ad73305c-1c93-11e7-96ae-71d922191ea3.png)

**Comment by Shushishtok** [comment] 2017-04-08 16:45
**Mirana**
Sacred Arrow's first damage instance doesn't crit (that code should be on the damagefilter and it isn't)
Leap doesn't get extra leap distance at night, both server and client sides.
Moonlight Shadow doesn't have a cast animation.

**Comment by Shushishtok** [comment] 2017-04-08 16:45
**Riki**
All skills have 4/3/2/1 (ult has 3/2/1) cooldown.
All skills have 4 levels (ult has 3).
Riki's Blink Strike has only 2 damage values: 200 and 555.
Riki's Blink Strike will not do anything if the target is out of range: might be annoying sometimes if you just want to make Riki run towards it and jump to it, but instead, Riki stays stationary and does nothing. 
Instead of showing a custom error, it might be better to just make Riki move towards it and try to jump to it normally, if no jump targets were found.
Riki's Blink Strike doesn't seem to slow turn speed of enemies: if it does work properly, then it definitely needs to be increase, as it takes almost no time to rotate yourself to face Riki.
Cloak and Dagger immediately apply when leveling up the skill instead of having a fade out time.
Riki has no custom talents in the talent tree.

**Comment by Shushishtok** [comment] 2017-04-08 16:45
**Ursa**
Doesn't get his innate skill.
Fury Swipes work fully on towers.

**Comment by Shushishtok** [comment] 2017-04-08 16:45
**Bane**
Has an ability layout of 4 while having 5 skills.
Seems like skill descriptions aren't updated at all, while talents are actually updated. "new" modifiers have no description at all.
Enfeeble's attribute reduction in descriptions should be with positives (it's a positive reduction..) instead of negatives.

**Comment by Shushishtok** [comment] 2017-04-08 16:45
**Dazzle**
Poison Touch: Description shows %movement_speed%% instead of a value. 
Shadow Wave: Bonus Armor doesn't seem to stay for 3 seconds like it's stated.. more like 1.5 seconds.
Shadow Wave: Doesn't state what is counted as "injured" for armor increase purposes.
Weave: I think the stack count is unneccesary, but that's my own opinon, not really a bug.

**Comment by Shushishtok** [comment] 2017-04-08 16:45
**Disruptor**
Disruptor's innate is not assigned at game start.
Ability layout of 4 skills while he has 5.
Static Storm: CAPS IN THE SKILL DESCRIPTION (the word "BY").

**Comment by Shushishtok** [comment] 2017-04-08 16:46
**Jakiro**
Fire Breath and Ice Breath: Description states -10% move slow - I prefer the values to be positives and not negatives. 
Fire Breath and Ice Breath: Jakiro literally can keep going and going and going forever until reaching the target location, without ever stopping.
Fire Breath: There is no visual effect for a target being hit by Fire Breath. Likewise for Ice Breath.
Fire Breath and Ice Breath: it seems that Jakiro will break trees much ahead of him, instead of strictly around his flying location
Ice Path: Targets do not have a particle of being frozen or for being slowed by the path's aftereffects.
Liquid Fire: Uses normal attack particle (not Liquid Fire's). 
Macrypyre's alt description "jakiro buffs increases..." - should be changed to "jakiro buff durations increases..."

**Comment by Shushishtok** [comment] 2017-04-08 16:46
**Lion**
Hex's secret Firetoad model doesn't go up in flames - throws "xxxx" insteaded.
Hex's secret Firetoad sound is not loaded in the soundevent.
Lion's Mana Drain Aura particle is invisible (probably not precached).
Lion's Mana Drain particles are huge. This is probably because the "laser" goes to the enemy's feet, while the rest of the drain particle goes to the enemy's hitloc.
Lion's Mana Drain particles do not follow allies (but follow enemies), and it goes purely to its feet instead to its hitloc.
Finger of Death: Frog Panic turns the main target to a frog immediately, removing muh skill cup dodge powa.

**Comment by Shushishtok** [comment] 2017-04-08 16:46
**Necrophos**
Heartstopper Aura: I still insist that the aura particle is too bright and is kinda invisible, and probably should use "stronger" green colors.
Sadist: Doesn't show the duration in the buff (so you can't really know when it's going to end)
Reaper's Scythe: Sick enemies have no particle on them to show the sickness: probably should have a status effect at least? maybe light green, to show nausea?

**Comment by Saniok88** [comment] 2017-04-09 17:39
IAS cap on ALL heroes seems to be uncapped (at least on Abaddon for sure)

**Comment by Shushishtok** [comment] 2017-04-11 20:12
@Saniok88 intended.

**Angelic Alliance**
Can be cast on self (shouldn't be possible)

**Comment by Shushishtok** [comment] 2017-04-11 20:14
**Tutela Plate**
Doesn't state how much damage block it has. (not Greater Parry's damage reduction)
Same for Crimson.

**Comment by Shushishtok** [comment] 2017-04-11 21:44
**Clinkz**
Missing some Searing Arrows special particles.

**Comment by Shushishtok** [comment] 2017-04-11 21:47
**Morbid Mask, MoM, Satanic, Vladimir**
Special attack particle missing, resulting in absolutely no attack particle for ranged heroes.

Vladmir only: Doesn't heal the attacker, but heals others affected by the aura.

**Comment by Shushishtok** [comment] 2017-04-21 18:15
**Omniknight**
When Omniknight heals a target with the double purification talent, it seems to give the target 2 stacks of amped heal instead of just one.

**Comment by Shushishtok** [comment] 2017-04-23 23:52
**Shadow Fiend**
PR is up, but I couldn't make it show the Scepter's effect in it, for reasons unknown.

**Comment by Shushishtok** [comment] 2017-05-01 23:01
**Sniper**
Passive range increase doesn't update (refresh) when leveling the ability.
Scepter Assassination doesn't target creeps.

**Comment by Shushishtok** [comment] 2017-05-12 09:01
Whew. Almost all bugs are fixed, except for Faceless Void (no talents and old description), Riki, and Bane.

**Comment by Shushishtok** [comment] 2017-05-13 01:26
Closing bug compilation. Remaining bugs are few and are listed on reddit.

**Closed by Shushishtok** 2017-05-13 01:26 UTC
Labels: bug
